### ISSUE TITLE
Should there be an option for patient reference input parameter? 

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/scheduling#16]
vs just the resource parameter itself
 if patient portal use case and other use case when provider scheduling

**Comment by cooperthompson** [comment]
In practice, I think just a patient resource should be fine.  That could have business identifiers (i.e. MRNs) that are probably at least as useful for patient matching as a FHIR ID/reference would be.

If we also wanted to allow a reference I'm not against that though.

**Comment by Healthedata1** [comment]
added reference to patient id to support GET syntax
