### ISSUE TITLE
Confirm that Operation$find  is a *resource based* (and not system based) operation

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/scheduling#18]
see definitions for resource vs system based operations in specification [here](http://build.fhir.org/operationdefinition-definitions.html#OperationDefinition.resource)

I suspect is a resource based operation but need to review with team.

**Comment by brettmarquard** [comment]
Please add operation name and add more details

**Comment by Healthedata1** [comment]
duplicate of #35
