### ISSUE TITLE
Does the discovery step fall into scope of Argo Scheduling?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/scheduling#19]
implementation issues or part of specification. 
Pros:
 - Touches servers

Cons:
 - Could be Application specific

Could document as "Server Best Practices" - does the discovery step fall into this?

**Comment by brettmarquard** [comment]
I think we should document as a 'nice to have' but not make it a prerequisite for the rest of the project.

**Comment by Healthedata1** [comment]
Decision to document as a future step.
