### ISSUE TITLE
Whether to use coding vs code + system for specialty and service inputs

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/scheduling#24]
using simple input allow using simpler `GET`  get syntax.  see examples.

This is simiar to the argument for using start and end instead of Period

**Comment by cooperthompson** [comment]
I would have thought we'd be using CodeableConcept for specialty and service.  And then using the token data type on the GET-style search.  Though I admit I'm not really sure how we mix and match the search param data types with the POST-body Parameter style input params.

**Comment by Healthedata1** [comment]
Decision to use string + token search parameter in order to use the GET syntax. Testing out in sprint.
