### ISSUE TITLE
Is patient registration in scope for this IG?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/scheduling#28]
See operation notes here: https://github.com/argonautproject/scheduling/wiki/Operations#patient-registrationlookup

How much of this in scope for this IG?
-  Document only where the patient registration occurs in the workflow?
-  Document how the patient registration transaction is performed using FHIR REST?
-  Other?

**Comment by Healthedata1** [comment]
agreed on today's call that guidance was needed...

for Patient scheduling identified two patterns:
 
- Patient portal:  patient known since logging in with Smart on FHIR /Oauth - no need to register

- Open Scheduling: at time of booking new patient will need be registered using RESTful POST operation. however the conditional create is done on the server side.  so document this behavior.
- Open Scheduling:  existing patient registered using RESTful POST operation. however since the conditional create is done on the server side the patient will be known.  so document this behavior.
- Open Scheduling but want check if existing patient for demographic information at beginning of workflow. =  ?Oauth/Smart (I forget)

- For (future) Provider Scheduling :  use Patient#match for MPI lookup.

#### Next Step: rewrite guidance in wiki and review

**Comment by Healthedata1** [comment]
partially updated.

**Comment by cooperthompson** [comment]
Eric,

I did some checking, and our current open scheduling solution actually prompts the patient for insurance information after the appointment is booked.  So I'd suggest our IG at least allow the insurance/coverage part of the registration to occur post-scheduling.

**Comment by Healthedata1** [comment]
applied in IG
