### ISSUE TITLE
Should patient cancel transaction support reason

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/scheduling#34]
Updated [Patient cancel](https://github.com/argonautproject/scheduling/wiki/Operations#end-user-amends-or-changes-appointment-details) to be a Patch operation.  Open issues on whether to support cancel reason either as text or code?

**Comment by Healthedata1** [comment]
- Add extension for CancelReason  (or StatusReason) to Appt  (  0..* type CodeableConcept )
- Add ability to have reason code/text in cancel interaction  (Patch)

**Comment by cooperthompson** [comment]
Here is a list of our base cancel reasons.  This is customer extensible, so we probably would make the value set binding also extensible.


Patient: Scheduled   from Wait List
Other: Error
Patient: Lack of Transportation
Other: Weather
Patient: Deceased
Patient: Unhappy/Changed Provider
Patient: Member Terminated
Patient: Moved
Provider: Discharged
Patient: Canceled via Patient Portal
Provider: Hospitalized
Other: No Interpreter Available
Provider: Edu/Meeting
Provider Personal
Other: Prep/Med/Results Unavailable
Patient: Pregnant
Provider: Labs Out of Acceptable Range
Prep/Med Incomplete
Other: Improper IV Access/Infiltrate IV
Patient: Feeling Better
Equipment Maintenance/Repair
Other: Financial
Other: Room/Resource Maintenance
Other: Schedule Order Error
Other: Silent Walk In Error
Provider: Oncology Treatment Plan Changes
Patient: Canceled via automated reminder system
Other: CMS Therapy Cap Service Not Authorized
Provider: MRI Screening Form Marked Do Not Proceed

**Comment by michelle-m-miller** [comment]
What is the proposed code system for these codes?

**Comment by michelle-m-miller** [comment]
Was there discussion (sorry I missed the last call) about status reason vs cancel reason?  We track codified reasons (also extensible) why any action was taken -- not just cancel, but also reschedule, etc.

Many similar codes.  This is not a complete list, but representative examples being:  bad weather, patient ill, patient refused procedure, equipment not available, patient needs other tests, prep incomplete, scheduled in error, patient deceased, patient was a no show etc.

**Comment by Healthedata1** [comment]
I added and [extension](http://build.fhir.org/ig/argonautproject/scheduling/StructureDefinition-extension-status-reason.html) to the Appointment Profile in the IG:   the published value set is rudimentary and stubbed after I was not able to find any suitable externable vocabularies.  I will udpate with these values.

**Comment by Healthedata1** [comment]
[applied](http://build.fhir.org/ig/argonautproject/scheduling/ValueSet-status-reason.html) and edited the codes a bit.  I created definition for most but some I did not understand and other I omitted as being overly specific like "Provider: MRI Screening Form Marked Do Not Proceed"

Cooper can you quickly review the definitions and fill in the blanks?  

Comments welcome but won't spend a lot of call time on it.  right now is example binding only and keeping it as a flat list.
