### ISSUE TITLE
Appointment/$find operation is only a resource level operation, not system level

### ISSUE THREAD

**Issue by cooperthompson** [argonautproject/scheduling#35]
http://build.fhir.org/ig/argonautproject/scheduling/OperationDefinition-appointment-find-sprint.html

The sprint version of the appointment.$find operation has a system level operation listed, however this operation should only be resource-level.

URL: [base]/$find

URL: [base]/Appointment/$find

**Comment by Healthedata1** [comment]
updated to be only a resource level operation

**Comment by Healthedata1** [comment]
applied change
