### ISSUE TITLE
A few proposed changes for the $find parameter data types

### ISSUE THREAD

**Issue by cooperthompson** [argonautproject/scheduling#36]
http://build.fhir.org/ig/argonautproject/scheduling/OperationDefinition-appointment-find-sprint.html

A few issues around data types:

The appt-type parameter is currently a string type.  Shouldn't that be a coding data type?
The provider parameter is currently a type uri.  Shouldn't that be a reference data type?

**Comment by brettmarquard** [comment]
Do you have a suggested value set?

**Comment by Healthedata1** [comment]
Rationale for types is to use simple parameter data types to allow using both `GET` and `POST` for Appointment$find: 
   
- Simple type ‘string’ instead of ‘Coding’  where the string type is same as [token search parameter](http://build.fhir.org/search.html#token) type
 - Simple type ‘uri’ instead of Reference where the uri is same as[ reference search parameter](http://build.fhir.org/search.html#reference)

**Comment by Healthedata1** [comment]
challenges for coding not sure of system - better if POST used coding.

**Comment by Healthedata1** [comment]
OperationDefinition defines the [search parameter type](http://build.fhir.org/operationdefinition-definitions.html#OperationDefinition.parameter.searchType) for strings. This is described in the documentation [here](http://build.fhir.org/ig/argonautproject/scheduling/OperationDefinition-appointment-find-sprint.html)?  

> This string parameter is interpreted as a Token search parameter. Each parameter value SHALL contain both the system property and the code property for a code using the general syntax specialty=[system]|[code]. See the examples below for how this is implemented.

Is this unclear or do we need to update the table to include a column for search parameter type?

**Comment by brettmarquard** [comment]
Does it state anywhere on the page why ' This string parameter is interpreted as a Token search parameter.'?

I think folks not involved will ask. I also think it's a good move to add search parameter type -- but I am not sure i like the idea of another column. Could we just add a note for the types that are string?

**Comment by Healthedata1** [comment]
already in documentation.  Suggestions to make it more obvious and clearer?

[image: Inline image 1]

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com <ehaas@healhtedatainc.com>

**Comment by brettmarquard** [comment]
Maybe something like – “FHIR allows a search parameter of type ‘string’ to be treated as different parameter types (e.g. number, date, reference, token). In this element, the string is to be interpreted as a Token search parameter.”

**Comment by Healthedata1** [comment]
document and render string data search parameters types better.   Gforge [#14092] for rendering

If unable to get IG-Pub updated then will update rendering in IG manually.

**Comment by Healthedata1** [comment]
OK I updated the operation to document and render the search token.  http://build.fhir.org/ig/argonautproject/scheduling/OperationDefinition-appointment-find.html

hope to close this one if this looks OK.
