### ISSUE TITLE
Clarity/split Appointment.$find provider property

### ISSUE THREAD

**Issue by cooperthompson** [argonautproject/scheduling#37]
The provider property still seems a little unclear.  I was talking with Brian, and we think splitting it out so we have three discrete properties would be good:

practitioner
organization
location (already there)

We can also clarify the help text to indicate that these properties are meant to answer the question "who would you prefer to provide care to you".  This could be a specific practitioner you've seen before, a specific clinic you want to go to, or a specific institution you have a relationship with.

**Comment by Healthedata1** [comment]
http://build.fhir.org/ig/argonautproject/scheduling/OperationDefinition-appointment-find-sprint.html

**Comment by Healthedata1** [comment]
Will update to make recommended changes.

**Comment by Healthedata1** [comment]
applied
