### ISSUE TITLE
Need to prioritize building a short list of ~10 appointment types

### ISSUE THREAD

**Issue by cooperthompson** [argonautproject/scheduling#39]
We should prioritize building a (probably Extensible) valueset of the >10 common appointment types for scheduling.

We will exclude visit type modifiers from this (i.e. new/existing pt, pediatric, etc.)

**Comment by Healthedata1** [comment]
already in core?


Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com <ehaas@healhtedatainc.com>

**Comment by Healthedata1** [comment]
See my comment for #38

**Comment by Healthedata1** [comment]
To clarify  here the "Appt-type"  = Patient Friendly Service codes that subsumes Appt-type, Specialty and Service

- Issue is whether can get a single list of codes that rules them all and bigger issue is whether could get broad agreement between clients ( 3rd Party Apps) and Servers ( EHRs)  on these concepts
- Could Provide a cross-mapping to Appt-type, Specialty and Service in the FHIR Resources  ( Slot, Appt, etc)
- Where would the translations occur client/server?

**Comment by brianpos** [comment]
The Appointment-type on the base appt resource is about the type of patient that will receive the service, the service-type/category/specialty is about what is to be done, and I think where the patient friendly service codes should go.

**Comment by Healthedata1** [comment]
I think appt-type is an appt attribute =  the circumstances around the
appointment.  I would like to see its definition clarified in the resources
 think I have a tracker to that effect.

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com <ehaas@healhtedatainc.com>

**Comment by daliboz** [comment]
Just to clarify - when we say "patient friendly" are we talking about having a display that is different than what the system/practitioner would see? If so, that's likely an extension off the display of the CodeableConcept rather than a value set. I'm curious why the *codeable* would need to be different for this use case.

**Comment by Healthedata1** [comment]
Yes you are right a patient friendly display could be an alternate
designation in the value set.  But I think the intent the comment was
trying to convey is to unify the service codes into a single list that does
it all.   Which is a tall order.

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com <ehaas@healhtedatainc.com>

**Comment by Healthedata1** [comment]
After further discussions about this, Are there a few <20 services that can be identified that cover the majority of use cases?

and should be somehow incorporate them into the spec either as a value set or a set of concept maps to the the existing terminologies and or examples?

**Comment by Healthedata1** [comment]
How to implement this?

- Use directly as input Parameters instead of Appt-type, Service and Specialty Codes
   - Pros:
      - Easier to manage on Client end
      - low hanging fruit ( "common stuff")
   - Cons:
      - Mal-alignment with Appt-type, Service and Specialty Codes in current FHIR resources - 
            shifting the mapping steps around
     - Consensus on a single list may be not be achievable

**Comment by cooperthompson** [comment]
Here is a list of some of our common visit types:

Breast Imaging
CONSULT
CT
Dental
DXA
ECHO
ECHO STRESS TEST
ED FOLLOW UP
EEG
EGD
ELECTROCARDIOGRAM
EVALUATION
FLU SHOT CLINIC
Fluoroscopy
FOLLOW UP
Home Heath Visit
INJECTION
Interventional Radiology
LAB
MINOR SURGERY
MRI
NEW PATIENT
Nuclear Medicine
OCCUPATIONAL THERAPY
OFFICE VISIT
PHYSICAL
POST-OP
PRE-ADMISSION TESTING VISIT
PRE-OP
PROCEDURE
PROCEDURE
SAME DAY
STRESS TEST
SURGERY
TREATMENT
ULTRASOUND
URGENT
Vision
WALK IN
WELL CHILD
X-ray

**Comment by Healthedata1** [comment]
Next steps: Review,  Implement as a single list With mapping to Service + Appt type.  (tentatively on client end)

**Comment by Healthedata1** [comment]
Are these visit types for patient scheduling and/or provider scheduling.  Do we need two list for each scenario?

**Comment by Healthedata1** [comment]
updated build to include visit-types  added mappings to service-type and appt-type and added to operation. http://build.fhir.org/ig/argonautproject/scheduling/OperationDefinition-appointment-find.html.

RE: mapping to Service + Appt type. Tentatively implemented on server end  - still need to update the examples..

Comments?

**Comment by Healthedata1** [comment]
creating extensible binding for service-type in Slot and Appointment profiles.  will keep open until after connectathon experience

**Comment by Healthedata1** [comment]
applied as a "visit-type" values set
