### ISSUE TITLE
What Service and SpecialtyTerminology ( code system ) should be used

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/scheduling#4]
Choices:
**Specialty:** 

1. http://www.fhir.org/guides/argonaut/pd/ValueSet-provider-specialty.html
   - make most sense since Argonaut artiafact steming from PD work
1. http://build.fhir.org/valueset-c80-practice-codes.html
   - from the FHiR spec
   - SNOMED CT codes

**Service:**
1. http://hl7.org/fhir/service-type
    - source: The Australian National Human Services Directory
     - no definitions :-(
1. Athena have metatype of appt types
1. Epic have metatype of appt types
1. CPT code 
    - AMA copyright issues
1. [ASC X12 External Code Source 958 Health Care Service Type Code](http://www.wpc-edi.com/reference/codelists/healthcare/health-care-service-type-codes/)
   -  X12 copyright issues

**Comment by Healthedata1** [comment]
Sent email to vendors to get input

> As discussed on our last Argo Scheduling Call having a standard set of codes for [ServiceType](http://build.fhir.org/appointment-definitions.html#Appointment.serviceType) and [Specialty](http://build.fhir.org/appointment-definitions.html#Appointment.specialty) are keys to interoperate.  We have not identified a satisfactory value set and so are looking to create them for this project.
> 
> The goals:
> - ~100 codes that could cover >80% of our initial use cases.
> - using using either existing code systems  ( e.g., SNOMED )  or new Argonaut based code system.
> - Transfer long term code system maintenance to an SDO
> 
> Strategy:
> - review the existing standard value sets (code sets) for:
>   - ServiceType
>     -  [ServiceType](http://build.fhir.org/valueset-service-type.html)
>   - Specialty
>     -  [Practice Setting Code Value Set](http://build.fhir.org/valueset-c80-practice-codes.html)
>     -  [Argonaut Provider Directory Provider Speciality (NUCC)](http://www.fhir.org/guides/argonaut/pd/ValueSet-provider-specialty.html)
> - Collect( ideally the most commonly used or sorted by usage ) code sets from the Argonaut Scheduling team and consolidate/aggregate the concepts.
>   -  Starter codes set from EHR Vendors
>   -  Code sets from 3rd Part Apps.
> -  Compare these concepts to standard codes-systems and map to them wher equivalent.
> 
> 
>   If possible, please provide me with your codesets for Service types and Specialty and I will take a first pass at aggregation and distribute for review.
> 
> 
>   Thanks,
> 
>   Eric
> 
> 
> 
> 
> 
> 
> 
>

**Comment by michelle-m-miller** [comment]
Eric, who from Cerner was included on your email to vendors?  Drew Torres and I have connected offline and we are leaning more towards SNOMED since NUCC is restricted to the US (we know Argonaut is US-based, but looking to maximize reuse in our mappings)

**Comment by Healthedata1** [comment]
Because this activity poses huge risks on our timeline, we are proposing limit the set of "standard" codes to <20 for the purposes of the Sprint and to get the ball rolling.

**Comment by Healthedata1** [comment]
base on 7/12 call will adopt SNOMED  for  Specialty and expose the exisitng concept mapping.  noting that the Snomed code lack  non clinical specialties. ( which we may have to add

> SNOMED 394658006 | Clinical specialty (qualifier value) |  
> 149 concepts
> Not a lot of community based concepts
> Look to other code systems. 

For Services codes I mapped Cooper supplied codes to SNOMED 

and created a separate code system for Type codes to add to exisitng fhir valueset

published codes  [Here](http://build.fhir.org/ig/argonautproject/scheduling/terminology.html)

**Comment by brettmarquard** [comment]
I am not requesting we reopen, but I want to make folks aware of a NUCC mapping to CMS provider types.

[Page describing](https://www.cms.gov/Medicare/Provider-Enrollment-and-Certification/MedicareProviderSupEnroll/Taxonomy.html)

[Direct link to mapping](https://www.cms.gov/Medicare/Provider-Enrollment-and-Certification/MedicareProviderSupEnroll/Downloads/TaxonomyCrosswalk.pdf)

**Comment by Healthedata1** [comment]
noted will add as a comment to IG

**Comment by Healthedata1** [comment]
added
