### ISSUE TITLE
Issues with Coverage Resource

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/scheduling#46]
(Note much of this is not related to the Scheduling IG but to the Coverage resource itself.)

1. `subscriber` is not always a registered patient, which leaves us with these options:
   - contained patient resource
   - bundle with patient somehow
1. `identifier` vs `subscriberId` may often be the same.
   - no identifier.type value for this
   - `subscriberId` is type string - why not type Identifier?
1. `grouping` structure is just weird
   - A better structure?:
     - Plan 0..*
       - Type 1..1 type codeableConcept ( valueset of 'plan', 'group', 'subplan', 'subgroup', etc. and allows for display)
       - identifier 1..1 type Identifier

**Comment by cooperthompson** [comment]
I agree - Coverage needs some modeling love.  PA and FM have had several discussions around subscriber IDs and identifiers and grouping...  I don't think we want to try to solve that can of worms here.

I think for our purposes (US-realm), we can probably get by with what is in the resource right now (for grouping and subscriber IDs.  For non-patient subscribers,  we'd probably want a contained _RelatedPerson_, not Patient.

**Comment by Healthedata1** [comment]
OK will close as out of scope.
