### ISSUE TITLE
Indication/diagnosis missing from $find operation

### ISSUE THREAD

**Issue by cooperthompson** [argonautproject/scheduling#53]
I don't see an indication/diagnosis input parameter on the $find operation.  I thought we had it in there at some point, and I don't remember if/why we took it out.

The "why" behind the appointment is pretty important for our scheduling algorithm, so I'd like to see that included as an option input parameter.

**Comment by Healthedata1** [comment]
OK I all add but we will  need to discuss value sets I'll stub into here a snomed problem value set.

**Comment by Healthedata1** [comment]
Added the `reason` input parameter to the [$find](https://argonautproject.github.io/scheduling/OperationDefinition-appointment-find.html) operation
