### ISSUE TITLE
Is the 2.4.3 response body total correct?

### ISSUE THREAD

**Issue by cooperthompson** [argonautproject/scheduling#66]
In [2.4.3](https://argonautproject.github.io/scheduling/patient-scheduling.html#example-2), the response body has a Bundle.total of 2.  However there is only one entry.  That single entry includes 2 resources, an Appointment and an OperationOutcome, but I thought the Bundle.total was a count of entries.

Or was part of the "snip" the close and open of the second entry?  If so we probably want to have the entry -related stuff not in the snip.

**Comment by Healthedata1** [comment]
fixed -  should be one entry  ( OO doesn't count and added the entry  related stuff...
